version: '3'

services:
  zmq_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5555:5555"

  zmq_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      server: zmq_server
    depends_on:
      - zmq_server
    # network_mode: "host"
