version: '3'

services:
  zmq_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "42069:42069"

  zmq_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      server: zmq_server
      # server: 10.8.5.102
    depends_on:
      - zmq_server
